# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'CSFYP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CSFYP
pod 'Firebase/Analytics'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Charts'
pod 'Firebase/Auth'
pod 'ZHDropDownMenu'

  target 'CSFYPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CSFYPUITests' do
    # Pods for testing
  end

end
